[package]
name = "ocpp-server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
chrono = "0.4.45"
env_logger = "0.11.11"
futures = "0.3.33"
log = "0.4.33"
ocpp_rs = "0.4.1"
rusqlite = { version = "0.40.2", features = ["chrono"] }
serde = { version = "^1", features = ["derive", "alloc"], default-features = false }
serde_json = { version = "^1", default-features = false, features = ["alloc", "arbitrary_precision"] }
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "signal"] }
tokio-tungstenite = "0.30.0"

[profile.release-slim]
inherits = "release"
strip = "symbols"
lto = "fat"
panic = "abort"
codegen-units = 1
