# ```
# cargo install cross --git https://github.com/cross-rs/cross
# cross build --profile release-slim --target aarch64-unknown-linux-gnu
#```
[build]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH", 
    "apt-get update && apt-get --assume-yes install libsqlite3-dev:$CROSS_DEB_ARCH"
]    
