# ```
# cargo install cross --git https://github.com/cross-rs/cross
# cross build --profile release-slim --target aarch64-unknown-linux-gnu --features bundled-sqlite,systemd
#
# current cross image sqlite3 version is too old for rusqlite:
# > undefined reference to sqlite3_prepare_v3
#
# so we need to compile with `--features bundled-sqlite` otherwise
# we could use:
#
# [build]
# pre-build = [
#     "dpkg --add-architecture $CROSS_DEB_ARCH", 
#     "apt-get update && apt-get --assume-yes install libsqlite3-dev:$CROSS_DEB_ARCH"
# ]    
#```
